server:
  port: 8282


security:
  oauth2:
    client:
      client-secret: pin
      access-token-validity-seconds: 3600
      authorized-grant-types: refresh_token, password, authorization_code, client_credentials
      scope: READ, WRITE
      client-id: mobile
    authorization:
      check-token-access: permitAll

spring:
  security:
    user:
      name: prabodha
      password: prabo123
      roles: ADMIN, USER
